# Generated by Django 5.0.1 on 2024-01-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclestatus',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
